/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _NetworkType {
    NetworkType_NETWORK_TYPE_NONE = 0,
    NetworkType_NETWORK_TYPE_WLAN = 1,
    NetworkType_NETWORK_TYPE_LAN = 2
} NetworkType;

/* Struct definitions */
typedef struct _BatteryInfo {
    float voltage;
    float percentage;
} BatteryInfo;

typedef struct _PowerOffReq {
    bool is_low_power;
} PowerOffReq;

typedef struct _DomainIdInfo {
    uint32_t id;
} DomainIdInfo;

typedef struct _HwInfoRes {
    uint64_t build_timestamp; /* unix epoch seconds (UTC) */
    char git_commit_hash[8];
} HwInfoRes;

typedef struct _NetworkInfoReq {
    char dummy_field;
} NetworkInfoReq;

typedef struct _PingReq {
    char dummy_field;
} PingReq;

/* ////////////////////////////
 MCU -> SBC
//////////////////////////// */
typedef struct _ToSbcMessage {
    pb_size_t which_data;
    union {
        BatteryInfo battery_info;
        PowerOffReq power_off_req;
        DomainIdInfo domain_id_info;
        HwInfoRes hw_info_res;
        NetworkInfoReq network_info_req;
        PingReq ping_req;
    } data;
} ToSbcMessage;

typedef PB_BYTES_ARRAY_T(4) IpInfo_ipv4_t;
typedef struct _IpInfo {
    IpInfo_ipv4_t ipv4; /* network byte order */
} IpInfo;

typedef struct _HwInfoReq {
    char dummy_field;
} HwInfoReq;

typedef struct _PowerOffEvt {
    char dummy_field;
} PowerOffEvt;

typedef struct _NetworkInfoRes {
    NetworkType type;
    char ssid[33];
    int32_t rssi;
    uint32_t frequency;
} NetworkInfoRes;

typedef struct _PingRes {
    float ping_ms;
} PingRes;

/* ////////////////////////////
 SBC -> MCU
//////////////////////////// */
typedef struct _ToMcuMessage {
    pb_size_t which_data;
    union {
        IpInfo ip_info;
        HwInfoReq hw_info_req;
        PowerOffEvt power_off_evt;
        NetworkInfoRes network_info_res;
        PingRes ping_res;
    } data;
} ToMcuMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _NetworkType_MIN NetworkType_NETWORK_TYPE_NONE
#define _NetworkType_MAX NetworkType_NETWORK_TYPE_LAN
#define _NetworkType_ARRAYSIZE ((NetworkType)(NetworkType_NETWORK_TYPE_LAN+1))












#define NetworkInfoRes_type_ENUMTYPE NetworkType



/* Initializer values for message structs */
#define ToSbcMessage_init_default                {0, {BatteryInfo_init_default}}
#define BatteryInfo_init_default                 {0, 0}
#define PowerOffReq_init_default                 {0}
#define DomainIdInfo_init_default                {0}
#define HwInfoRes_init_default                   {0, ""}
#define NetworkInfoReq_init_default              {0}
#define PingReq_init_default                     {0}
#define ToMcuMessage_init_default                {0, {IpInfo_init_default}}
#define IpInfo_init_default                      {{0, {0}}}
#define HwInfoReq_init_default                   {0}
#define PowerOffEvt_init_default                 {0}
#define NetworkInfoRes_init_default              {_NetworkType_MIN, "", 0, 0}
#define PingRes_init_default                     {0}
#define ToSbcMessage_init_zero                   {0, {BatteryInfo_init_zero}}
#define BatteryInfo_init_zero                    {0, 0}
#define PowerOffReq_init_zero                    {0}
#define DomainIdInfo_init_zero                   {0}
#define HwInfoRes_init_zero                      {0, ""}
#define NetworkInfoReq_init_zero                 {0}
#define PingReq_init_zero                        {0}
#define ToMcuMessage_init_zero                   {0, {IpInfo_init_zero}}
#define IpInfo_init_zero                         {{0, {0}}}
#define HwInfoReq_init_zero                      {0}
#define PowerOffEvt_init_zero                    {0}
#define NetworkInfoRes_init_zero                 {_NetworkType_MIN, "", 0, 0}
#define PingRes_init_zero                        {0}

/* Field tags (for use in manual encoding/decoding) */
#define BatteryInfo_voltage_tag                  1
#define BatteryInfo_percentage_tag               2
#define PowerOffReq_is_low_power_tag             1
#define DomainIdInfo_id_tag                      1
#define HwInfoRes_build_timestamp_tag            1
#define HwInfoRes_git_commit_hash_tag            2
#define ToSbcMessage_battery_info_tag            1
#define ToSbcMessage_power_off_req_tag           2
#define ToSbcMessage_domain_id_info_tag          3
#define ToSbcMessage_hw_info_res_tag             4
#define ToSbcMessage_network_info_req_tag        5
#define ToSbcMessage_ping_req_tag                6
#define IpInfo_ipv4_tag                          1
#define NetworkInfoRes_type_tag                  1
#define NetworkInfoRes_ssid_tag                  2
#define NetworkInfoRes_rssi_tag                  3
#define NetworkInfoRes_frequency_tag             4
#define PingRes_ping_ms_tag                      1
#define ToMcuMessage_ip_info_tag                 1
#define ToMcuMessage_hw_info_req_tag             2
#define ToMcuMessage_power_off_evt_tag           3
#define ToMcuMessage_network_info_res_tag        4
#define ToMcuMessage_ping_res_tag                5

/* Struct field encoding specification for nanopb */
#define ToSbcMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,battery_info,data.battery_info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,power_off_req,data.power_off_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,domain_id_info,data.domain_id_info),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,hw_info_res,data.hw_info_res),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,network_info_req,data.network_info_req),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,ping_req,data.ping_req),   6)
#define ToSbcMessage_CALLBACK NULL
#define ToSbcMessage_DEFAULT NULL
#define ToSbcMessage_data_battery_info_MSGTYPE BatteryInfo
#define ToSbcMessage_data_power_off_req_MSGTYPE PowerOffReq
#define ToSbcMessage_data_domain_id_info_MSGTYPE DomainIdInfo
#define ToSbcMessage_data_hw_info_res_MSGTYPE HwInfoRes
#define ToSbcMessage_data_network_info_req_MSGTYPE NetworkInfoReq
#define ToSbcMessage_data_ping_req_MSGTYPE PingReq

#define BatteryInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    percentage,        2)
#define BatteryInfo_CALLBACK NULL
#define BatteryInfo_DEFAULT NULL

#define PowerOffReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_low_power,      1)
#define PowerOffReq_CALLBACK NULL
#define PowerOffReq_DEFAULT NULL

#define DomainIdInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define DomainIdInfo_CALLBACK NULL
#define DomainIdInfo_DEFAULT NULL

#define HwInfoRes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   build_timestamp,   1) \
X(a, STATIC,   SINGULAR, STRING,   git_commit_hash,   2)
#define HwInfoRes_CALLBACK NULL
#define HwInfoRes_DEFAULT NULL

#define NetworkInfoReq_FIELDLIST(X, a) \

#define NetworkInfoReq_CALLBACK NULL
#define NetworkInfoReq_DEFAULT NULL

#define PingReq_FIELDLIST(X, a) \

#define PingReq_CALLBACK NULL
#define PingReq_DEFAULT NULL

#define ToMcuMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,ip_info,data.ip_info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,hw_info_req,data.hw_info_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,power_off_evt,data.power_off_evt),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,network_info_res,data.network_info_res),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,ping_res,data.ping_res),   5)
#define ToMcuMessage_CALLBACK NULL
#define ToMcuMessage_DEFAULT NULL
#define ToMcuMessage_data_ip_info_MSGTYPE IpInfo
#define ToMcuMessage_data_hw_info_req_MSGTYPE HwInfoReq
#define ToMcuMessage_data_power_off_evt_MSGTYPE PowerOffEvt
#define ToMcuMessage_data_network_info_res_MSGTYPE NetworkInfoRes
#define ToMcuMessage_data_ping_res_MSGTYPE PingRes

#define IpInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    ipv4,              1)
#define IpInfo_CALLBACK NULL
#define IpInfo_DEFAULT NULL

#define HwInfoReq_FIELDLIST(X, a) \

#define HwInfoReq_CALLBACK NULL
#define HwInfoReq_DEFAULT NULL

#define PowerOffEvt_FIELDLIST(X, a) \

#define PowerOffEvt_CALLBACK NULL
#define PowerOffEvt_DEFAULT NULL

#define NetworkInfoRes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              3) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         4)
#define NetworkInfoRes_CALLBACK NULL
#define NetworkInfoRes_DEFAULT NULL

#define PingRes_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    ping_ms,           1)
#define PingRes_CALLBACK NULL
#define PingRes_DEFAULT NULL

extern const pb_msgdesc_t ToSbcMessage_msg;
extern const pb_msgdesc_t BatteryInfo_msg;
extern const pb_msgdesc_t PowerOffReq_msg;
extern const pb_msgdesc_t DomainIdInfo_msg;
extern const pb_msgdesc_t HwInfoRes_msg;
extern const pb_msgdesc_t NetworkInfoReq_msg;
extern const pb_msgdesc_t PingReq_msg;
extern const pb_msgdesc_t ToMcuMessage_msg;
extern const pb_msgdesc_t IpInfo_msg;
extern const pb_msgdesc_t HwInfoReq_msg;
extern const pb_msgdesc_t PowerOffEvt_msg;
extern const pb_msgdesc_t NetworkInfoRes_msg;
extern const pb_msgdesc_t PingRes_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ToSbcMessage_fields &ToSbcMessage_msg
#define BatteryInfo_fields &BatteryInfo_msg
#define PowerOffReq_fields &PowerOffReq_msg
#define DomainIdInfo_fields &DomainIdInfo_msg
#define HwInfoRes_fields &HwInfoRes_msg
#define NetworkInfoReq_fields &NetworkInfoReq_msg
#define PingReq_fields &PingReq_msg
#define ToMcuMessage_fields &ToMcuMessage_msg
#define IpInfo_fields &IpInfo_msg
#define HwInfoReq_fields &HwInfoReq_msg
#define PowerOffEvt_fields &PowerOffEvt_msg
#define NetworkInfoRes_fields &NetworkInfoRes_msg
#define PingRes_fields &PingRes_msg

/* Maximum encoded size of messages (where known) */
#define BatteryInfo_size                         10
#define DomainIdInfo_size                        6
#define HwInfoReq_size                           0
#define HwInfoRes_size                           20
#define IpInfo_size                              6
#define MESSAGES_PB_H_MAX_SIZE                   ToMcuMessage_size
#define NetworkInfoReq_size                      0
#define NetworkInfoRes_size                      48
#define PingReq_size                             0
#define PingRes_size                             5
#define PowerOffEvt_size                         0
#define PowerOffReq_size                         2
#define ToMcuMessage_size                        50
#define ToSbcMessage_size                        22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
