/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ToSbcMessage, ToSbcMessage, AUTO)


PB_BIND(BatteryInfo, BatteryInfo, AUTO)


PB_BIND(PowerOffReq, PowerOffReq, AUTO)


PB_BIND(DomainIdInfo, DomainIdInfo, AUTO)


PB_BIND(HwInfoRes, HwInfoRes, AUTO)


PB_BIND(NetworkInfoReq, NetworkInfoReq, AUTO)


PB_BIND(PingReq, PingReq, AUTO)


PB_BIND(ToMcuMessage, ToMcuMessage, AUTO)


PB_BIND(IpInfo, IpInfo, AUTO)


PB_BIND(HwInfoReq, HwInfoReq, AUTO)


PB_BIND(PowerOffEvt, PowerOffEvt, AUTO)


PB_BIND(NetworkInfoRes, NetworkInfoRes, AUTO)


PB_BIND(PingRes, PingRes, AUTO)





