# Logging (global defaults)
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_PROCESS_THREAD_SLEEP_MS=50
CONFIG_REQUIRES_FLOAT_PRINTF=y

CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_PWM=y
