// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// https://wokwi.com/tools/pioasm                     //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// pwm_capture //
// ----------- //

#define pwm_capture_wrap_target 0
#define pwm_capture_wrap 14

static const uint16_t pwm_capture_program_instructions[] = {
    //     .wrap_target
    0xa04b, //  0: mov    y, !null
    0xa02b, //  1: mov    x, !null
    0x2020, //  2: wait   0 pin, 0
    0x20a0, //  3: wait   1 pin, 0
    0x0086, //  4: jmp    y--, 6
    0x0000, //  5: jmp    0
    0x00c4, //  6: jmp    pin, 4
    0x00ca, //  7: jmp    pin, 10
    0x0047, //  8: jmp    x--, 7
    0x0000, //  9: jmp    0
    0xa0ca, // 10: mov    isr, !y
    0x8000, // 11: push   noblock
    0xa0c9, // 12: mov    isr, !x
    0x8000, // 13: push   noblock
    0xc030, // 14: irq    wait 0 rel
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_capture_program = {
    .instructions = pwm_capture_program_instructions,
    .length = 15,
    .origin = -1,
};

static inline pio_sm_config pwm_capture_program_get_default_config(uint offset) {
  pio_sm_config c = pio_get_default_sm_config();
  sm_config_set_wrap(&c, offset + pwm_capture_wrap_target, offset + pwm_capture_wrap);
  return c;
}
#endif
