/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "include/messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mechaship_sbc_SbcMessage, mechaship_sbc_SbcMessage, AUTO)


PB_BIND(mechaship_sbc_IpInfo, mechaship_sbc_IpInfo, AUTO)


PB_BIND(mechaship_sbc_HwInfo, mechaship_sbc_HwInfo, AUTO)


PB_BIND(mechaship_sbc_PowerOff, mechaship_sbc_PowerOff, AUTO)


PB_BIND(mechaship_sbc_NetworkInfo, mechaship_sbc_NetworkInfo, AUTO)


PB_BIND(mechaship_sbc_PingResponse, mechaship_sbc_PingResponse, AUTO)







