/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MECHASHIP_SBC_INCLUDE_MESSAGES_PB_H_INCLUDED
#define PB_MECHASHIP_SBC_INCLUDE_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 명령 종류 (C의 command 번호를 그대로 사용해도 되고, 새로운 enum 정의도 가능) */
typedef enum _mechaship_sbc_CommandType {
    mechaship_sbc_CommandType_COMMAND_NONE = 0,
    mechaship_sbc_CommandType_COMMAND_IP = 1,
    mechaship_sbc_CommandType_COMMAND_SEND_HW_INFO = 2, /* IN */
    mechaship_sbc_CommandType_COMMAND_POWER_OFF = 3, /* PO */
    mechaship_sbc_CommandType_COMMAND_NETWORK_INFO = 4, /* IW */
    mechaship_sbc_CommandType_COMMAND_PING_RESPONSE = 5 /* PG */
} mechaship_sbc_CommandType;

typedef enum _mechaship_sbc_NetworkType {
    mechaship_sbc_NetworkType_NETWORK_NONE = 0,
    mechaship_sbc_NetworkType_NETWORK_WLAN = 1,
    mechaship_sbc_NetworkType_NETWORK_LAN = 2
} mechaship_sbc_NetworkType;

/* Struct definitions */
/* IP 보고: 기존 C는 "x.x.x.x" 를 4바이트 uint32 로 만들고 있음 */
typedef struct _mechaship_sbc_IpInfo {
    uint32_t ipv4; /* host byte order or network byte order는 구현에서 합의 */
} mechaship_sbc_IpInfo;

/* IN */
typedef struct _mechaship_sbc_HwInfo {
    pb_callback_t date;
    pb_callback_t time;
    pb_callback_t git_commit;
} mechaship_sbc_HwInfo;

/* PO */
typedef struct _mechaship_sbc_PowerOff { /* no field (필요시 reason 등 추가 가능) */
    char dummy_field;
} mechaship_sbc_PowerOff;

/* IW */
typedef struct _mechaship_sbc_NetworkInfo {
    mechaship_sbc_NetworkType type;
    pb_callback_t ssid;
    int32_t rssi;
    uint32_t frequency;
} mechaship_sbc_NetworkInfo;

/* PG */
typedef struct _mechaship_sbc_PingResponse {
    float ping_ms;
} mechaship_sbc_PingResponse;

/* 공통적으로 들어오는 SBC 메시지 */
typedef struct _mechaship_sbc_SbcMessage {
    mechaship_sbc_CommandType type;
    /* 각 타입별 payload */
    bool has_ip_info;
    mechaship_sbc_IpInfo ip_info;
    bool has_hw_info;
    mechaship_sbc_HwInfo hw_info;
    bool has_power_off;
    mechaship_sbc_PowerOff power_off;
    bool has_network_info;
    mechaship_sbc_NetworkInfo network_info;
    bool has_ping_response;
    mechaship_sbc_PingResponse ping_response;
} mechaship_sbc_SbcMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _mechaship_sbc_CommandType_MIN mechaship_sbc_CommandType_COMMAND_NONE
#define _mechaship_sbc_CommandType_MAX mechaship_sbc_CommandType_COMMAND_PING_RESPONSE
#define _mechaship_sbc_CommandType_ARRAYSIZE ((mechaship_sbc_CommandType)(mechaship_sbc_CommandType_COMMAND_PING_RESPONSE+1))

#define _mechaship_sbc_NetworkType_MIN mechaship_sbc_NetworkType_NETWORK_NONE
#define _mechaship_sbc_NetworkType_MAX mechaship_sbc_NetworkType_NETWORK_LAN
#define _mechaship_sbc_NetworkType_ARRAYSIZE ((mechaship_sbc_NetworkType)(mechaship_sbc_NetworkType_NETWORK_LAN+1))

#define mechaship_sbc_SbcMessage_type_ENUMTYPE mechaship_sbc_CommandType




#define mechaship_sbc_NetworkInfo_type_ENUMTYPE mechaship_sbc_NetworkType



/* Initializer values for message structs */
#define mechaship_sbc_SbcMessage_init_default    {_mechaship_sbc_CommandType_MIN, false, mechaship_sbc_IpInfo_init_default, false, mechaship_sbc_HwInfo_init_default, false, mechaship_sbc_PowerOff_init_default, false, mechaship_sbc_NetworkInfo_init_default, false, mechaship_sbc_PingResponse_init_default}
#define mechaship_sbc_IpInfo_init_default        {0}
#define mechaship_sbc_HwInfo_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define mechaship_sbc_PowerOff_init_default      {0}
#define mechaship_sbc_NetworkInfo_init_default   {_mechaship_sbc_NetworkType_MIN, {{NULL}, NULL}, 0, 0}
#define mechaship_sbc_PingResponse_init_default  {0}
#define mechaship_sbc_SbcMessage_init_zero       {_mechaship_sbc_CommandType_MIN, false, mechaship_sbc_IpInfo_init_zero, false, mechaship_sbc_HwInfo_init_zero, false, mechaship_sbc_PowerOff_init_zero, false, mechaship_sbc_NetworkInfo_init_zero, false, mechaship_sbc_PingResponse_init_zero}
#define mechaship_sbc_IpInfo_init_zero           {0}
#define mechaship_sbc_HwInfo_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define mechaship_sbc_PowerOff_init_zero         {0}
#define mechaship_sbc_NetworkInfo_init_zero      {_mechaship_sbc_NetworkType_MIN, {{NULL}, NULL}, 0, 0}
#define mechaship_sbc_PingResponse_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define mechaship_sbc_IpInfo_ipv4_tag            1
#define mechaship_sbc_HwInfo_date_tag            1
#define mechaship_sbc_HwInfo_time_tag            2
#define mechaship_sbc_HwInfo_git_commit_tag      3
#define mechaship_sbc_NetworkInfo_type_tag       1
#define mechaship_sbc_NetworkInfo_ssid_tag       2
#define mechaship_sbc_NetworkInfo_rssi_tag       3
#define mechaship_sbc_NetworkInfo_frequency_tag  4
#define mechaship_sbc_PingResponse_ping_ms_tag   1
#define mechaship_sbc_SbcMessage_type_tag        1
#define mechaship_sbc_SbcMessage_ip_info_tag     2
#define mechaship_sbc_SbcMessage_hw_info_tag     3
#define mechaship_sbc_SbcMessage_power_off_tag   4
#define mechaship_sbc_SbcMessage_network_info_tag 5
#define mechaship_sbc_SbcMessage_ping_response_tag 6

/* Struct field encoding specification for nanopb */
#define mechaship_sbc_SbcMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ip_info,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hw_info,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  power_off,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  network_info,      5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping_response,     6)
#define mechaship_sbc_SbcMessage_CALLBACK NULL
#define mechaship_sbc_SbcMessage_DEFAULT NULL
#define mechaship_sbc_SbcMessage_ip_info_MSGTYPE mechaship_sbc_IpInfo
#define mechaship_sbc_SbcMessage_hw_info_MSGTYPE mechaship_sbc_HwInfo
#define mechaship_sbc_SbcMessage_power_off_MSGTYPE mechaship_sbc_PowerOff
#define mechaship_sbc_SbcMessage_network_info_MSGTYPE mechaship_sbc_NetworkInfo
#define mechaship_sbc_SbcMessage_ping_response_MSGTYPE mechaship_sbc_PingResponse

#define mechaship_sbc_IpInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ipv4,              1)
#define mechaship_sbc_IpInfo_CALLBACK NULL
#define mechaship_sbc_IpInfo_DEFAULT NULL

#define mechaship_sbc_HwInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   date,              1) \
X(a, CALLBACK, SINGULAR, STRING,   time,              2) \
X(a, CALLBACK, SINGULAR, STRING,   git_commit,        3)
#define mechaship_sbc_HwInfo_CALLBACK pb_default_field_callback
#define mechaship_sbc_HwInfo_DEFAULT NULL

#define mechaship_sbc_PowerOff_FIELDLIST(X, a) \

#define mechaship_sbc_PowerOff_CALLBACK NULL
#define mechaship_sbc_PowerOff_DEFAULT NULL

#define mechaship_sbc_NetworkInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              3) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         4)
#define mechaship_sbc_NetworkInfo_CALLBACK pb_default_field_callback
#define mechaship_sbc_NetworkInfo_DEFAULT NULL

#define mechaship_sbc_PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    ping_ms,           1)
#define mechaship_sbc_PingResponse_CALLBACK NULL
#define mechaship_sbc_PingResponse_DEFAULT NULL

extern const pb_msgdesc_t mechaship_sbc_SbcMessage_msg;
extern const pb_msgdesc_t mechaship_sbc_IpInfo_msg;
extern const pb_msgdesc_t mechaship_sbc_HwInfo_msg;
extern const pb_msgdesc_t mechaship_sbc_PowerOff_msg;
extern const pb_msgdesc_t mechaship_sbc_NetworkInfo_msg;
extern const pb_msgdesc_t mechaship_sbc_PingResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define mechaship_sbc_SbcMessage_fields &mechaship_sbc_SbcMessage_msg
#define mechaship_sbc_IpInfo_fields &mechaship_sbc_IpInfo_msg
#define mechaship_sbc_HwInfo_fields &mechaship_sbc_HwInfo_msg
#define mechaship_sbc_PowerOff_fields &mechaship_sbc_PowerOff_msg
#define mechaship_sbc_NetworkInfo_fields &mechaship_sbc_NetworkInfo_msg
#define mechaship_sbc_PingResponse_fields &mechaship_sbc_PingResponse_msg

/* Maximum encoded size of messages (where known) */
/* mechaship_sbc_SbcMessage_size depends on runtime parameters */
/* mechaship_sbc_HwInfo_size depends on runtime parameters */
/* mechaship_sbc_NetworkInfo_size depends on runtime parameters */
#define MECHASHIP_SBC_INCLUDE_MESSAGES_PB_H_MAX_SIZE mechaship_sbc_IpInfo_size
#define mechaship_sbc_IpInfo_size                6
#define mechaship_sbc_PingResponse_size          5
#define mechaship_sbc_PowerOff_size              0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
